Args = --no-fallback \
       -H:+ReportExceptionStackTraces \
       --features=clj_easy.graal_build_time.InitClojureClasses \
       --initialize-at-build-time=com.fasterxml.jackson \
       --initialize-at-build-time=clojure.lang.XMLHandler \
       --enable-url-protocols=http,https \
       -J-Dclojure.compiler.direct-linking=true \
       -J-Dclojure.spec.skip-macros=true
